export interface Scholarship {
  name: string;
  coverage: string;
}

export interface University {
  name: string;
  shortName: string;
  location: string;
  type: 'State' | 'Private' | 'LUC';
  color: string;
  logoUrl: string;
  examName: string;
  examDate: string;
  appDeadline: string;
  resultsDate: string;
  requirements: string[];
  scholarships: Scholarship[];
  scholarshipUrl: string;
  specializations: string[];
  website: string;
  isOpen: boolean;
}

export const UNIVERSITIES: University[] = [
  {
    name: 'University of the Philippines System',
    shortName: 'UP System',
    location: 'Diliman, Quezon City',
    type: 'State',
    color: '#7B1113',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/ca/UP_seal.png',
    examName: 'UPCAT',
    examDate: 'Aug 10–11, 2026',
    appDeadline: 'Jun 1, 2026',
    resultsDate: 'Dec 2026',
    requirements: ['Form 137', 'PSA Birth Certificate', 'Good Moral Character', 'Medical Certificate', 'Application Form (online)'],
    scholarships: [
      { name: 'UP Socialized Tuition (ST)', coverage: 'Full tuition waiver based on bracket' },
    ],
    scholarshipUrl: 'https://osss.up.edu.ph',
    specializations: ['Engineering', 'Science', 'Law', 'Arts', 'Social Sciences'],
    website: 'https://upcat.up.edu.ph',
    isOpen: true,
  },
  {
    name: 'Ateneo de Manila University',
    shortName: 'Ateneo Manila',
    location: 'Loyola Heights, Quezon City',
    type: 'Private',
    color: '#003DA5',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Ateneo_de_Manila_University_seal.png',
    examName: 'ACET',
    examDate: 'Sep 2026',
    appDeadline: 'Aug 15, 2026',
    resultsDate: 'Nov 2026',
    requirements: ['Grade 10 Report Card', 'ACET Application Form', 'Recommendation Letter'],
    scholarships: [
      { name: 'Ateneo Financial Assistance', coverage: 'Need-based discount' },
    ],
    scholarshipUrl: 'https://osa.ateneo.edu/scholarships',
    specializations: ['Business', 'Humanities', 'Social Sciences', 'Management'],
    website: 'https://www.ateneo.edu/acet',
    isOpen: false,
  },
  {
    name: 'De La Salle University',
    shortName: 'DLSU',
    location: 'Taft Avenue, Manila',
    type: 'Private',
    color: '#005236',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d5/De_La_Salle_University_Seal.svg',
    examName: 'DLSU-CET',
    examDate: 'Oct 2026',
    appDeadline: 'Sep 15, 2026',
    resultsDate: 'Dec 2026',
    requirements: ['Online Application Form', 'Grade 10 Report Card', 'School Certification'],
    scholarships: [
      { name: 'DLSU Academic Scholarship', coverage: 'Tuple waiver based on CET' },
    ],
    scholarshipUrl: 'https://www.dlsu.edu.ph/admissions/scholarships/',
    specializations: ['Business', 'Engineering', 'Computer Science', 'Economics'],
    website: 'https://www.dlsu.edu.ph',
    isOpen: false,
  },
  {
    name: 'University of Santo Tomas',
    shortName: 'UST',
    location: 'España Blvd, Manila',
    type: 'Private',
    color: '#DEAD00',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e9/UST_logo.png',
    examName: 'USTET',
    examDate: 'Oct 2026',
    appDeadline: 'Sep 30, 2026',
    resultsDate: 'Nov 2026',
    requirements: ['Online Exam Permit', 'Form 138 or 137', 'Good Moral Certificate'],
    scholarships: [
      { name: 'UST Academic Excellence', coverage: 'Tuition waiver' },
    ],
    scholarshipUrl: 'https://www.ust.edu.ph/admissions/scholarships/',
    specializations: ['Medicine', 'Nursing', 'Architecture', 'Pharmacy', 'Engineering'],
    website: 'https://www.ust.edu.ph',
    isOpen: false,
  },
  {
    name: 'Far Eastern University',
    shortName: 'FEU',
    location: 'Nicanor Reyes St, Manila',
    type: 'Private',
    color: '#007A3D',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a8/Far_Eastern_University_seal.png',
    examName: 'FEUAT',
    examDate: 'Oct–Nov 2026',
    appDeadline: 'Oct 30, 2026',
    resultsDate: 'Dec 2026',
    requirements: ['Report Card', 'PSA Birth Certificate', 'Good Moral Certificate'],
    scholarships: [
      { name: 'FEU Academic Scholarship', coverage: '100% or 50% tuition waiver' },
    ],
    scholarshipUrl: 'https://www.feu.edu.ph/admissions/financial-aid/',
    specializations: ['Accountancy', 'Medical Technology', 'Nursing', 'Architecture'],
    website: 'https://www.feu.edu.ph',
    isOpen: false,
  },
  {
    name: 'Mapúa University',
    shortName: 'Mapúa',
    location: 'Intramuros, Manila',
    type: 'Private',
    color: '#CC0000',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b6/Mapua_University_seal.png',
    examName: 'MUCAT',
    examDate: 'Rolling Admission',
    appDeadline: 'Rolling',
    resultsDate: 'Rolling',
    requirements: ['Online Application', 'Form 138', 'Entrance Exam Permit'],
    scholarships: [
      { name: 'Mapúa Academic Scholarship', coverage: 'Full tuition based on MUCAT' },
    ],
    scholarshipUrl: 'https://www.mapua.edu.ph/admissions/scholarships',
    specializations: ['Engineering', 'Architecture', 'Information Technology'],
    website: 'https://www.mapua.edu.ph',
    isOpen: true,
  },
  {
    name: 'Polytechnic University of the Philippines',
    shortName: 'PUP',
    location: 'Anonas, Manila',
    type: 'State',
    color: '#8B0000',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9d/Polytechnic_University_of_the_Philippines.png',
    examName: 'PUPCET',
    examDate: 'Nov 2026',
    appDeadline: 'Oct 1, 2026',
    resultsDate: 'Jan 2027',
    requirements: ['Form 138', 'PSA Birth Certificate', 'Accomplished Form'],
    scholarships: [
      { name: 'PUP Socialized Tuition', coverage: 'Free tuition (RA 10931)' },
    ],
    scholarshipUrl: 'https://www.pup.edu.ph/scholarships',
    specializations: ['Engineering', 'Accountancy', 'Education', 'Business Administration'],
    website: 'https://www.pup.edu.ph',
    isOpen: false,
  },
  {
    name: 'Mindanao State University – IIT',
    shortName: 'MSU-IIT',
    location: 'Iligan City, Lanao del Norte',
    type: 'State',
    color: '#006400',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/31/MSU-IIT_Seal.png',
    examName: 'MSUSCAT',
    examDate: 'Mar 2027',
    appDeadline: 'Feb 2027',
    resultsDate: 'Apr 2027',
    requirements: ['Form 138', 'PSA Birth Certificate'],
    scholarships: [
      { name: 'MSU Free Tuition', coverage: 'Full tuition waiver' },
    ],
    scholarshipUrl: 'https://www.msuiit.edu.ph/offices/osa/scholarships.php',
    specializations: ['Engineering', 'Science', 'Computer Science', 'Education'],
    website: 'https://www.msuiit.edu.ph',
    isOpen: false,
  },
  {
    name: 'Bicol University',
    shortName: 'Bicol U',
    location: 'Legazpi City, Albay',
    type: 'State',
    color: '#B22222',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Bicol_University_seal.png',
    examName: 'BUCAT',
    examDate: 'Feb 2027',
    appDeadline: 'Jan 15, 2027',
    resultsDate: 'Mar 2027',
    requirements: ['Grade 12 Report Card', 'Good Moral Certificate'],
    scholarships: [
      { name: 'BU Free Tuition', coverage: 'Free tuition for all enrolled' },
    ],
    scholarshipUrl: 'https://www.bicol-u.edu.ph',
    specializations: ['Education', 'Nursing', 'Engineering', 'Agriculture'],
    website: 'https://www.bicol-u.edu.ph',
    isOpen: false,
  },
  {
    name: 'Adamson University',
    shortName: 'AdU',
    location: 'San Marcelino, Manila',
    type: 'Private',
    color: '#003087',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Adamson_University_logo.png',
    examName: 'AUCAT',
    examDate: 'Oct–Nov 2026',
    appDeadline: 'Nov 30, 2026',
    resultsDate: 'Dec 2026',
    requirements: ['Online Application', 'Form 138'],
    scholarships: [
      { name: 'AdU Academic Scholarship', coverage: 'Partial to full tuition' },
    ],
    scholarshipUrl: 'https://www.adamson.edu.ph/scholarship',
    specializations: ['Engineering', 'Pharmacy', 'Architecture', 'Business'],
    website: 'https://www.adamson.edu.ph',
    isOpen: false,
  },
  {
    name: 'Ateneo de Davao University',
    shortName: 'AdDU',
    location: 'Davao City',
    type: 'Private',
    color: '#002D72',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/27/Ateneo_de_Davao_University_Seal.png',
    examName: 'AdDU-AT',
    examDate: 'Nov 2026',
    appDeadline: 'Oct 2026',
    resultsDate: 'Dec 2026',
    requirements: ['Application Form', 'Form 138'],
    scholarships: [
      { name: 'AdDU Merit Scholarship', coverage: 'Up to 100% tuition' },
    ],
    scholarshipUrl: 'https://www.addu.edu.ph/financial-aid',
    specializations: ['Business', 'Law', 'Engineering', 'Information Technology'],
    website: 'https://www.addu.edu.ph',
    isOpen: false,
  },
  {
    name: 'Saint Louis University',
    shortName: 'SLU Baguio',
    location: 'Baguio City',
    type: 'Private',
    color: '#003087',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a5/Saint_Louis_University_%28Philippines%29_seal.png',
    examName: 'SLUAT',
    examDate: 'Oct–Dec 2026',
    appDeadline: 'Rolling',
    resultsDate: 'Rolling',
    requirements: ['Application Form', 'Form 138'],
    scholarships: [
      { name: 'SLU Academic Scholarship', coverage: 'Discount based on score' },
    ],
    scholarshipUrl: 'https://www.slu.edu.ph/scholarships',
    specializations: ['Medicine', 'Engineering', 'Nursing', 'Architecture'],
    website: 'https://www.slu.edu.ph',
    isOpen: true,
  },
  {
    name: 'University of San Carlos',
    shortName: 'USC Cebu',
    location: 'Cebu City',
    type: 'Private',
    color: '#003087',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8b/University_of_San_Carlos_seal.png',
    examName: 'USC-AT',
    examDate: 'Oct–Nov 2026',
    appDeadline: 'Oct 2026',
    resultsDate: 'Dec 2026',
    requirements: ['Application Form', 'Form 138'],
    scholarships: [
      { name: 'USC Academic Excellence Award', coverage: 'Tuition waiver' },
    ],
    scholarshipUrl: 'https://www.usc.edu.ph/admissions/scholarships',
    specializations: ['Engineering', 'Architecture', 'Law', 'Business'],
    website: 'https://www.usc.edu.ph',
    isOpen: false,
  },
  {
    name: 'Xavier University',
    shortName: 'XU',
    location: 'Cagayan de Oro City',
    type: 'Private',
    color: '#003087',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8a/Xavier_University_Ateneo_de_Cagayan_seal.png',
    examName: 'XUCAT',
    examDate: 'Nov 2026',
    appDeadline: 'Oct 2026',
    resultsDate: 'Dec 2026',
    requirements: ['Online Application', 'Form 138'],
    scholarships: [
      { name: 'XU Merit Scholarship', coverage: 'Partial to full tuition' },
    ],
    scholarshipUrl: 'https://www.xu.edu.ph/admissions/scholarships',
    specializations: ['Agriculture', 'Nursing', 'Engineering', 'Business'],
    website: 'https://www.xu.edu.ph',
    isOpen: false,
  },
  {
    name: 'Silliman University',
    shortName: 'Silliman',
    location: 'Dumaguete City',
    type: 'Private',
    color: '#4B0082',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Silliman_University_seal.png',
    examName: 'SUAT',
    examDate: 'Jan–Feb 2027',
    appDeadline: 'Dec 2026',
    resultsDate: 'Feb 2027',
    requirements: ['Application Form', 'Form 138'],
    scholarships: [
      { name: 'SU Academic Scholarship', coverage: 'Merit-based discount' },
    ],
    scholarshipUrl: 'https://www.su.edu.ph/financial-assistance',
    specializations: ['Nursing', 'Marine Biology', 'Education', 'Performing Arts'],
    website: 'https://www.su.edu.ph',
    isOpen: false,
  },
  {
    name: 'Central Philippine University',
    shortName: 'CPU',
    location: 'Iloilo City',
    type: 'Private',
    color: '#8B0030',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e1/Central_Philippine_University_logo.jpg',
    examName: 'CPUAT',
    examDate: 'Jan–Feb 2027',
    appDeadline: 'Jan 2027',
    resultsDate: 'Feb 2027',
    requirements: ['Application Form', 'Form 138'],
    scholarships: [
      { name: 'CPU Merit Scholarship', coverage: 'Tuition reduction' },
    ],
    scholarshipUrl: 'https://www.cpu.edu.ph/admissions/scholarships',
    specializations: ['Nursing', 'Agriculture', 'Engineering', 'Business'],
    website: 'https://www.cpu.edu.ph',
    isOpen: false,
  },
  {
    name: 'Polytechnic University – Laguna',
    shortName: 'LSPU',
    location: 'San Pablo City, Laguna',
    type: 'State',
    color: '#006400',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c4/Laguna_State_Polytechnic_University_logo.png',
    examName: 'LSPUCAT',
    examDate: 'Feb 2027',
    appDeadline: 'Jan 2027',
    resultsDate: 'Mar 2027',
    requirements: ['Form 138', 'Good Moral Certificate'],
    scholarships: [
      { name: 'Free Tuition', coverage: 'Tuition-free' },
    ],
    scholarshipUrl: 'https://www.lspu.edu.ph',
    specializations: ['Agriculture', 'Education', 'Computer Studies', 'Engineering'],
    website: 'https://www.lspu.edu.ph',
    isOpen: false,
  },
  {
    name: 'Bulacan State University',
    shortName: 'BulSU',
    location: 'Malolos, Bulacan',
    type: 'State',
    color: '#003087',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/64/Bulacan_State_University_logo.png',
    examName: 'BulSUCAT',
    examDate: 'Jan–Feb 2027',
    appDeadline: 'Dec 2026',
    resultsDate: 'Feb 2027',
    requirements: ['Form 138', 'PSA Birth Certificate'],
    scholarships: [
      { name: 'Free Tuition (RA 10931)', coverage: 'Tuition waiver' },
    ],
    scholarshipUrl: 'https://www.bulsu.edu.ph/scholarships',
    specializations: ['Engineering', 'Education', 'Information Technology', 'Architecture'],
    website: 'https://www.bulsu.edu.ph',
    isOpen: false,
  },
  {
    name: 'Cavite State University',
    shortName: 'CvSU',
    location: 'Indang, Cavite',
    type: 'State',
    color: '#006400',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/0e/Cavite_State_University_seal.png',
    examName: 'CvSUCAT',
    examDate: 'Feb 2027',
    appDeadline: 'Jan 2027',
    resultsDate: 'Feb 2027',
    requirements: ['Form 138', 'PSA Birth Certificate'],
    scholarships: [
      { name: 'Free Tuition', coverage: 'Full tuition waiver' },
    ],
    scholarshipUrl: 'https://www.cvsu.edu.ph',
    specializations: ['Agriculture', 'Veterinary Medicine', 'Engineering', 'Education'],
    website: 'https://www.cvsu.edu.ph',
    isOpen: false,
  },
  {
    name: 'Batangas State University',
    shortName: 'BatStateU',
    location: 'Batangas City',
    type: 'State',
    color: '#8B0000',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/78/BatStateU.png',
    examName: 'BatStateU-CAT',
    examDate: 'Feb 2027',
    appDeadline: 'Jan 15, 2027',
    resultsDate: 'Feb 2027',
    requirements: ['Form 138', 'PSA Birth Certificate'],
    scholarships: [
      { name: 'Free Tuition', coverage: 'Tuition-free' },
    ],
    scholarshipUrl: 'https://www.batstate-u.edu.ph/scholarships',
    specializations: ['Engineering', 'Architecture', 'Information Technology', 'Education'],
    website: 'https://www.batstate-u.edu.ph',
    isOpen: false,
  },
  {
    name: 'Philippine Normal University',
    shortName: 'PNU',
    location: 'Taft Avenue, Manila',
    type: 'State',
    color: '#003087',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/38/Philippine_Normal_University_logo.png',
    examName: 'PNUCAT',
    examDate: 'Feb 2027',
    appDeadline: 'Jan 2027',
    resultsDate: 'Mar 2027',
    requirements: ['Form 138', 'Medical Certificate'],
    scholarships: [
      { name: 'Free Tuition (RA 10931)', coverage: 'Tuition-free' },
    ],
    scholarshipUrl: 'https://www.pnu.edu.ph/scholarships',
    specializations: ['Education', 'Psychology', 'Literature', 'Languages'],
    website: 'https://www.pnu.edu.ph',
    isOpen: false,
  },
  {
    name: 'Technological University of the Philippines',
    shortName: 'TUP Manila',
    location: 'Ayala Blvd, Manila',
    type: 'State',
    color: '#8B0000',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c1/Technological_University_of_the_Philippines_seal.png',
    examName: 'TUPCAT',
    examDate: 'Feb 2027',
    appDeadline: 'Jan 2027',
    resultsDate: 'Mar 2027',
    requirements: ['Form 138', 'PSA Birth Certificate'],
    scholarships: [
      { name: 'Free Tuition', coverage: 'Tuition waiver' },
    ],
    scholarshipUrl: 'https://www.tup.edu.ph',
    specializations: ['Engineering Technology', 'Architecture', 'Industrial Education'],
    website: 'https://www.tup.edu.ph',
    isOpen: false,
  },
  {
    name: 'University of the East',
    shortName: 'UE Manila',
    location: 'Claro M. Recto, Manila',
    type: 'Private',
    color: '#CC0000',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f8/University_of_the_East_seal.png',
    examName: 'UEAT',
    examDate: 'Rolling',
    appDeadline: 'Rolling',
    resultsDate: 'Rolling',
    requirements: ['Application Form', 'Form 138'],
    scholarships: [
      { name: 'UE Academic Scholarship', coverage: 'Tuition discount' },
    ],
    scholarshipUrl: 'https://www.ue.edu.ph/financial-aid',
    specializations: ['Dentistry', 'Business', 'Engineering', 'Information Technology'],
    website: 'https://www.ue.edu.ph',
    isOpen: true,
  },
  {
    name: 'National University Philippines',
    shortName: 'NU',
    location: 'Manila & BGC',
    type: 'Private',
    color: '#003087',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ed/National_University_Philippines_seal.png',
    examName: 'NUAT',
    examDate: 'Rolling',
    appDeadline: 'Rolling',
    resultsDate: 'Rolling',
    requirements: ['Application Form', 'Form 138'],
    scholarships: [
      { name: 'NU Academic Scholarship', coverage: 'Full or partial tuition' },
    ],
    scholarshipUrl: 'https://national-u.edu.ph/admissions/scholarships/',
    specializations: ['Architecture', 'Engineering', 'Nursing', 'Business'],
    website: 'https://national-u.edu.ph',
    isOpen: true,
  },
  {
    name: 'San Beda University',
    shortName: 'San Beda',
    location: 'Mendiola, Manila',
    type: 'Private',
    color: '#8B0000',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7d/San_Beda_University_seal.png',
    examName: 'SBU-AT',
    examDate: 'Oct–Nov 2026',
    appDeadline: 'Oct 2026',
    resultsDate: 'Dec 2026',
    requirements: ['Application Form', 'Form 138'],
    scholarships: [
      { name: 'SBU Academic Scholarship', coverage: 'Merit-based grant' },
    ],
    scholarshipUrl: 'https://www.sanbeda.edu.ph/scholarships',
    specializations: ['Law', 'Accountancy', 'Business', 'Medicine'],
    website: 'https://www.sanbeda.edu.ph',
    isOpen: false,
  },
];
